apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: poi
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: poi
  ports:
    - protocol: TCP
      name: poi-http
      port: 80 # port you hit
      targetPort: 8080 # port inside container